version: '3.8'

volumes:
  mysql-data:
networks:
  spring-boot-mysql-network:
    name: spring-boot-mysql-network
services:
  mysqldb:
    image: mysql:lts
    #command: --mysql-native-password=ON
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=copy_file_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=4/OobApyR7HLWGWR/2xzGVAzYnqoLzFbCxT/kNVVDXs=
      - MYSQL_ROOT_PASSWORD=wxxQizIsNjvotettRgDCF9bsRRaucM2OUq6+z/J3cIY=
    networks:
      - spring-boot-mysql-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      interval: 3s
      timeout: 30s

  copy-file:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/copy_file_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=4/OobApyR7HLWGWR/2xzGVAzYnqoLzFbCxT/kNVVDXs=
    networks:
      - spring-boot-mysql-network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysqldb
      - MYSQL_ROOT_PASSWORD=wxxQizIsNjvotettRgDCF9bsRRaucM2OUq6+z/J3cIY=
    depends_on:
      - mysqldb
    networks:
      - spring-boot-mysql-network
